name: Build and test

on:
  push:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ktlint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-lint
      - name: spotless
        run: ./gradlew spotlessCheck --scan

  api_check:
    name: API check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-APICheck
      - name: API check
        run: ./gradlew apiCheck --scan

  debug_build:
    name: Debug build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-build
      - name: Build
        run: ./gradlew assembleDebug --scan

  test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-test
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest