name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - name: Cache Gradle and wrapper
        uses: actions/cache@v3.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle executable
        run: chmod +x ./gradlew

  api_check:
    name: API check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-APICheck
      - name: API check
        run: ./gradlew apiCheck --scan

  debug_build:
    name: Debug build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-build
      - name: Build
        run: ./gradlew assembleDebug --scan

  test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-test
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest