name: Pull request CI checks

on: [pull_request]

env:
  BUILD_CACHE_AWS_REGION: ${{ secrets.BUILD_CACHE_AWS_REGION }}
  BUILD_CACHE_AWS_BUCKET: ${{ secrets.BUILD_CACHE_AWS_BUCKET }}
  BUILD_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_CACHE_AWS_ACCESS_KEY_ID }}
  BUILD_CACHE_AWS_SECRET_KEY: ${{ secrets.BUILD_CACHE_AWS_SECRET_KEY }}

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ktlint
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-lint
      - name: spotless
        run: ./gradlew spotlessCheck --scan

  api_check:
    name: API check
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-APICheck
      - name: API check
        run: ./gradlew apiCheck --scan

  debug_build:
    name: Debug build
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-build
      - name: Build
        run: ./gradlew assembleDebug --scan

  test:
    name: Unit tests
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-test
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test results
        uses: actions/upload-artifact@v4.4.3
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest